/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java_final;

import static java_final.Funcionalidades.calcularParcialDescuentoTotal;
import static java_final.Funcionalidades.calcularSubtotal;
import static java_final.Funcionalidades.eliminarDatosLabel;
import static java_final.Funcionalidades.eliminarDatosText;
import javax.swing.JLabel;
import javax.swing.JTextField;

/**
 *
 * @author tineo
 */
public class Final extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public Final() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg_top = new javax.swing.JPanel();
        lb_title = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bg_bottom = new javax.swing.JPanel();
        panel_subtitles = new javax.swing.JPanel();
        lb_subtitles2 = new javax.swing.JLabel();
        panel_item1 = new javax.swing.JPanel();
        cbox_1 = new javax.swing.JCheckBox();
        tf_13 = new javax.swing.JTextField();
        lb_12 = new javax.swing.JLabel();
        lb_11 = new javax.swing.JLabel();
        tf_14 = new javax.swing.JTextField();
        panel_item2 = new javax.swing.JPanel();
        cbox_2 = new javax.swing.JCheckBox();
        tf_23 = new javax.swing.JTextField();
        lb_22 = new javax.swing.JLabel();
        lb_21 = new javax.swing.JLabel();
        tf_24 = new javax.swing.JTextField();
        panel_item3 = new javax.swing.JPanel();
        cbox_3 = new javax.swing.JCheckBox();
        tf_33 = new javax.swing.JTextField();
        lb_32 = new javax.swing.JLabel();
        lb_31 = new javax.swing.JLabel();
        tf_34 = new javax.swing.JTextField();
        panel_item4 = new javax.swing.JPanel();
        cbox_4 = new javax.swing.JCheckBox();
        tf_43 = new javax.swing.JTextField();
        lb_42 = new javax.swing.JLabel();
        lb_41 = new javax.swing.JLabel();
        tf_44 = new javax.swing.JTextField();
        lb_importe_int = new javax.swing.JLabel();
        lb_descuento_str = new javax.swing.JLabel();
        lb_importe_str1 = new javax.swing.JLabel();
        lb_descuento_int = new javax.swing.JLabel();
        lb_total_str = new javax.swing.JLabel();
        lb_total_int = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btn_resultado = new javax.swing.JButton();
        btn_nuevo = new javax.swing.JButton();
        lb_alerta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        bg_top.setBackground(new java.awt.Color(102, 0, 255));
        bg_top.setForeground(new java.awt.Color(255, 255, 255));

        lb_title.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        lb_title.setForeground(new java.awt.Color(255, 255, 255));
        lb_title.setText("FACTURAS");

        jButton1.setBackground(new java.awt.Color(102, 0, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 32)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("x");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bg_topLayout = new javax.swing.GroupLayout(bg_top);
        bg_top.setLayout(bg_topLayout);
        bg_topLayout.setHorizontalGroup(
            bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_topLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_title)
                .addGap(248, 248, 248)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bg_topLayout.setVerticalGroup(
            bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_topLayout.createSequentialGroup()
                .addGroup(bg_topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_topLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bg_topLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lb_title, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        bg_bottom.setBackground(new java.awt.Color(255, 255, 255));

        panel_subtitles.setBackground(new java.awt.Color(153, 153, 153));

        lb_subtitles2.setBackground(new java.awt.Color(102, 255, 102));
        lb_subtitles2.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lb_subtitles2.setForeground(new java.awt.Color(0, 0, 0));
        lb_subtitles2.setText("     S/N     Descripción     Precio Unitario     Cantidad     Subtotal     ");
        lb_subtitles2.setToolTipText("");
        lb_subtitles2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));

        javax.swing.GroupLayout panel_subtitlesLayout = new javax.swing.GroupLayout(panel_subtitles);
        panel_subtitles.setLayout(panel_subtitlesLayout);
        panel_subtitlesLayout.setHorizontalGroup(
            panel_subtitlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_subtitles2)
        );
        panel_subtitlesLayout.setVerticalGroup(
            panel_subtitlesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lb_subtitles2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panel_item1.setBackground(new java.awt.Color(255, 255, 255));

        cbox_1.setFont(new java.awt.Font("MesloLGS NF", 0, 36)); // NOI18N
        cbox_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_1ActionPerformed(evt);
            }
        });

        tf_13.setBackground(new java.awt.Color(204, 204, 204));
        tf_13.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_13.setForeground(new java.awt.Color(51, 51, 51));
        tf_13.setText("0");
        tf_13.setEnabled(false);
        tf_13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_13ActionPerformed(evt);
            }
        });

        lb_12.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_12.setForeground(new java.awt.Color(51, 51, 51));
        lb_12.setText("80.00");

        lb_11.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_11.setForeground(new java.awt.Color(51, 51, 51));
        lb_11.setText("Amoxicilina 500 Mg.");

        tf_14.setBackground(new java.awt.Color(204, 204, 204));
        tf_14.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_14.setForeground(new java.awt.Color(51, 51, 51));
        tf_14.setText("0.0");
        tf_14.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_14.setEnabled(false);
        tf_14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_item1Layout = new javax.swing.GroupLayout(panel_item1);
        panel_item1.setLayout(panel_item1Layout);
        panel_item1Layout.setHorizontalGroup(
            panel_item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(cbox_1)
                .addGap(38, 38, 38)
                .addComponent(lb_11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_12)
                .addGap(98, 98, 98)
                .addComponent(tf_13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tf_14, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panel_item1Layout.setVerticalGroup(
            panel_item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(lb_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tf_14)
            .addComponent(tf_13)
        );

        panel_item2.setBackground(new java.awt.Color(255, 255, 255));

        cbox_2.setFont(new java.awt.Font("MesloLGS NF", 0, 36)); // NOI18N
        cbox_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_2ActionPerformed(evt);
            }
        });

        tf_23.setBackground(new java.awt.Color(204, 204, 204));
        tf_23.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_23.setForeground(new java.awt.Color(51, 51, 51));
        tf_23.setText("0");
        tf_23.setEnabled(false);

        lb_22.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_22.setForeground(new java.awt.Color(51, 51, 51));
        lb_22.setText("50.00");

        lb_21.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_21.setForeground(new java.awt.Color(51, 51, 51));
        lb_21.setText("Ibuprofeno 125 Mg.");

        tf_24.setBackground(new java.awt.Color(204, 204, 204));
        tf_24.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_24.setForeground(new java.awt.Color(51, 51, 51));
        tf_24.setText("0.0");
        tf_24.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_24.setEnabled(false);
        tf_24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_24ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_item2Layout = new javax.swing.GroupLayout(panel_item2);
        panel_item2.setLayout(panel_item2Layout);
        panel_item2Layout.setHorizontalGroup(
            panel_item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(cbox_2)
                .addGap(38, 38, 38)
                .addComponent(lb_21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_22)
                .addGap(98, 98, 98)
                .addComponent(tf_23, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tf_24, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panel_item2Layout.setVerticalGroup(
            panel_item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(lb_21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tf_24)
            .addComponent(tf_23)
        );

        panel_item3.setBackground(new java.awt.Color(255, 255, 255));

        cbox_3.setFont(new java.awt.Font("MesloLGS NF", 0, 36)); // NOI18N
        cbox_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_3ActionPerformed(evt);
            }
        });

        tf_33.setBackground(new java.awt.Color(204, 204, 204));
        tf_33.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_33.setForeground(new java.awt.Color(51, 51, 51));
        tf_33.setText("0");
        tf_33.setEnabled(false);

        lb_32.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_32.setForeground(new java.awt.Color(51, 51, 51));
        lb_32.setText("65.00");

        lb_31.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_31.setForeground(new java.awt.Color(51, 51, 51));
        lb_31.setText("Antalgina 100 Mg.");

        tf_34.setBackground(new java.awt.Color(204, 204, 204));
        tf_34.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_34.setForeground(new java.awt.Color(51, 51, 51));
        tf_34.setText("0.0");
        tf_34.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_34.setEnabled(false);
        tf_34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_34ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_item3Layout = new javax.swing.GroupLayout(panel_item3);
        panel_item3.setLayout(panel_item3Layout);
        panel_item3Layout.setHorizontalGroup(
            panel_item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item3Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(cbox_3)
                .addGap(38, 38, 38)
                .addComponent(lb_31)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_32)
                .addGap(98, 98, 98)
                .addComponent(tf_33, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tf_34, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panel_item3Layout.setVerticalGroup(
            panel_item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(lb_31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tf_34)
            .addComponent(tf_33)
        );

        panel_item4.setBackground(new java.awt.Color(255, 255, 255));

        cbox_4.setFont(new java.awt.Font("MesloLGS NF", 0, 36)); // NOI18N
        cbox_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_4ActionPerformed(evt);
            }
        });

        tf_43.setBackground(new java.awt.Color(204, 204, 204));
        tf_43.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_43.setForeground(new java.awt.Color(51, 51, 51));
        tf_43.setText("0");
        tf_43.setEnabled(false);

        lb_42.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_42.setForeground(new java.awt.Color(51, 51, 51));
        lb_42.setText("40.00");

        lb_41.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_41.setForeground(new java.awt.Color(51, 51, 51));
        lb_41.setText("Penicilina 100 gr.");

        tf_44.setBackground(new java.awt.Color(204, 204, 204));
        tf_44.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        tf_44.setForeground(new java.awt.Color(51, 51, 51));
        tf_44.setText("0.0");
        tf_44.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        tf_44.setEnabled(false);
        tf_44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_44ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_item4Layout = new javax.swing.GroupLayout(panel_item4);
        panel_item4.setLayout(panel_item4Layout);
        panel_item4Layout.setHorizontalGroup(
            panel_item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item4Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(cbox_4)
                .addGap(38, 38, 38)
                .addComponent(lb_41)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lb_42)
                .addGap(98, 98, 98)
                .addComponent(tf_43, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(tf_44, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
        panel_item4Layout.setVerticalGroup(
            panel_item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_item4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbox_4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
            .addComponent(lb_41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lb_42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tf_44)
            .addComponent(tf_43)
        );

        lb_importe_int.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_importe_int.setForeground(new java.awt.Color(51, 51, 51));
        lb_importe_int.setText("0.0");

        lb_descuento_str.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_descuento_str.setForeground(new java.awt.Color(51, 51, 51));
        lb_descuento_str.setText("Descuento S/.");

        lb_importe_str1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_importe_str1.setForeground(new java.awt.Color(51, 51, 51));
        lb_importe_str1.setText("Importe parcial S/.");

        lb_descuento_int.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        lb_descuento_int.setForeground(new java.awt.Color(51, 51, 51));
        lb_descuento_int.setText("0.0");

        lb_total_str.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lb_total_str.setForeground(new java.awt.Color(51, 51, 51));
        lb_total_str.setText("Total S/.");

        lb_total_int.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        lb_total_int.setForeground(new java.awt.Color(51, 51, 51));
        lb_total_int.setText("0.0");

        jSeparator1.setBackground(new java.awt.Color(45, 132, 138));
        jSeparator1.setForeground(new java.awt.Color(45, 132, 138));

        btn_resultado.setBackground(new java.awt.Color(102, 0, 255));
        btn_resultado.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btn_resultado.setForeground(new java.awt.Color(255, 255, 255));
        btn_resultado.setText("Calcular");
        btn_resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resultadoActionPerformed(evt);
            }
        });

        btn_nuevo.setBackground(new java.awt.Color(45, 132, 138));
        btn_nuevo.setFont(new java.awt.Font("Monospaced", 1, 24)); // NOI18N
        btn_nuevo.setForeground(new java.awt.Color(255, 255, 255));
        btn_nuevo.setText("Nuevo");
        btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoActionPerformed(evt);
            }
        });

        lb_alerta.setBackground(new java.awt.Color(255, 0, 0));
        lb_alerta.setFont(new java.awt.Font("Monospaced", 1, 18)); // NOI18N
        lb_alerta.setForeground(new java.awt.Color(255, 0, 0));
        lb_alerta.setText(" ");

        javax.swing.GroupLayout bg_bottomLayout = new javax.swing.GroupLayout(bg_bottom);
        bg_bottom.setLayout(bg_bottomLayout);
        bg_bottomLayout.setHorizontalGroup(
            bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_bottomLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btn_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_bottomLayout.createSequentialGroup()
                .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, bg_bottomLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_importe_str1)
                            .addComponent(lb_descuento_str))
                        .addGap(41, 41, 41)
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lb_importe_int, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_descuento_int, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bg_bottomLayout.createSequentialGroup()
                                .addGap(122, 122, 122)
                                .addComponent(lb_total_str)
                                .addGap(31, 31, 31)
                                .addComponent(lb_total_int, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bg_bottomLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lb_alerta)
                                .addGap(29, 29, 29))))
                    .addGroup(bg_bottomLayout.createSequentialGroup()
                        .addContainerGap(53, Short.MAX_VALUE)
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panel_item1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_subtitles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panel_item4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))))
                .addGap(44, 44, 44))
        );
        bg_bottomLayout.setVerticalGroup(
            bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bg_bottomLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panel_subtitles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel_item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel_item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel_item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(panel_item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bg_bottomLayout.createSequentialGroup()
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_importe_str1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_importe_int, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_descuento_str, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_descuento_int, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bg_bottomLayout.createSequentialGroup()
                        .addComponent(lb_alerta)
                        .addGap(10, 10, 10)
                        .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb_total_str, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb_total_int, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(bg_bottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_nuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg_top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bg_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg_top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bg_bottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf_14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_14ActionPerformed

    private void cbox_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_1ActionPerformed
        // TODO add your handling code here:
        if (cbox_1.isSelected()) {
            tf_13.setEnabled(true);
            tf_13.requestFocusInWindow();
            tf_13.selectAll();
        } else {
            tf_13.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_1ActionPerformed

    private void cbox_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_2ActionPerformed
        // TODO add your handling code here:
        if (cbox_2.isSelected()) {
            tf_23.setEnabled(true);
            tf_23.requestFocusInWindow();
            tf_23.selectAll();
        } else {
            tf_23.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_2ActionPerformed

    private void tf_24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_24ActionPerformed

    private void cbox_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_3ActionPerformed
        // TODO add your handling code here:
        if (cbox_3.isSelected()) {
            tf_33.setEnabled(true);
            tf_33.requestFocusInWindow();
            tf_33.selectAll();
        } else {
            tf_33.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_3ActionPerformed

    private void tf_34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_34ActionPerformed

    private void cbox_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_4ActionPerformed
        // TODO add your handling code here:
        if (cbox_4.isSelected()) {
            tf_43.setEnabled(true);
            tf_43.requestFocusInWindow();
            tf_43.selectAll();
        } else {
            tf_43.setEnabled(false);
        }
    }//GEN-LAST:event_cbox_4ActionPerformed

    private void tf_44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_44ActionPerformed

    private void btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoActionPerformed
        // TODO add your handling code here:
        JTextField[] array_textfield = {
            tf_13, tf_14, tf_23, tf_24, tf_33, tf_34, tf_43, tf_44
        };
        JLabel[] array_label = {lb_importe_int, lb_descuento_int, lb_total_int};
        eliminarDatosText(array_textfield);
        eliminarDatosLabel(array_label);
        lb_alerta.setText("");
    }//GEN-LAST:event_btn_nuevoActionPerformed

    private void tf_13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_13ActionPerformed

    private void btn_resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resultadoActionPerformed
        // TODO add your handling code here:

        tf_14.setText(calcularSubtotal(lb_12, tf_13, lb_alerta));
        tf_24.setText(calcularSubtotal(lb_22, tf_23, lb_alerta));
        tf_34.setText(calcularSubtotal(lb_32, tf_33, lb_alerta));
        tf_44.setText(calcularSubtotal(lb_42, tf_43, lb_alerta));

        JTextField[] array_textfield = {tf_14, tf_24, tf_34, tf_44};

        // Retorna y modifica suma array (parcial, descuento, total)
        String[] costos = calcularParcialDescuentoTotal(array_textfield);

        lb_importe_int.setText(costos[0]);
        lb_descuento_int.setText(costos[1]);
        lb_total_int.setText(costos[2]);

    }//GEN-LAST:event_btn_resultadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Final.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Final().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg_bottom;
    private javax.swing.JPanel bg_top;
    private javax.swing.JButton btn_nuevo;
    private javax.swing.JButton btn_resultado;
    private javax.swing.JCheckBox cbox_1;
    private javax.swing.JCheckBox cbox_2;
    private javax.swing.JCheckBox cbox_3;
    private javax.swing.JCheckBox cbox_4;
    private javax.swing.JButton jButton1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lb_11;
    private javax.swing.JLabel lb_12;
    private javax.swing.JLabel lb_21;
    private javax.swing.JLabel lb_22;
    private javax.swing.JLabel lb_31;
    private javax.swing.JLabel lb_32;
    private javax.swing.JLabel lb_41;
    private javax.swing.JLabel lb_42;
    private javax.swing.JLabel lb_alerta;
    private javax.swing.JLabel lb_descuento_int;
    private javax.swing.JLabel lb_descuento_str;
    private javax.swing.JLabel lb_importe_int;
    private javax.swing.JLabel lb_importe_str1;
    private javax.swing.JLabel lb_subtitles2;
    private javax.swing.JLabel lb_title;
    private javax.swing.JLabel lb_total_int;
    private javax.swing.JLabel lb_total_str;
    private javax.swing.JPanel panel_item1;
    private javax.swing.JPanel panel_item2;
    private javax.swing.JPanel panel_item3;
    private javax.swing.JPanel panel_item4;
    private javax.swing.JPanel panel_subtitles;
    private javax.swing.JTextField tf_13;
    private javax.swing.JTextField tf_14;
    private javax.swing.JTextField tf_23;
    private javax.swing.JTextField tf_24;
    private javax.swing.JTextField tf_33;
    private javax.swing.JTextField tf_34;
    private javax.swing.JTextField tf_43;
    private javax.swing.JTextField tf_44;
    // End of variables declaration//GEN-END:variables
}
